/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddToHomeScreen: typeof import('./src/components/schedule/toolbar/AddToHomeScreen.vue')['default']
    CalendarExportDialog: typeof import('./src/components/schedule/CalendarExportDialog.vue')['default']
    Checkbox: typeof import('./src/components/global/Checkbox.vue')['default']
    CopyText: typeof import('./src/components/global/CopyText.vue')['default']
    Day: typeof import('./src/components/schedule/list/Day.vue')['default']
    Dialog: typeof import('./src/components/global/Dialog.vue')['default']
    LectureInfo: typeof import('./src/components/schedule/list/LectureInfo.vue')['default']
    Schedule: typeof import('./src/components/schedule/Schedule.vue')['default']
    SchedulePicker: typeof import('./src/components/schedule/SchedulePicker.vue')['default']
    ScheduleTable: typeof import('./src/components/schedule/table/ScheduleTable.vue')['default']
    ScheduleTableCell: typeof import('./src/components/schedule/table/ScheduleTableCell.vue')['default']
    Spinner: typeof import('./src/components/global/Spinner.vue')['default']
    TimeSlot: typeof import('./src/components/schedule/list/TimeSlot.vue')['default']
    Toast: typeof import('./src/components/global/Toast.vue')['default']
    Toaster: typeof import('./src/components/global/Toaster.vue')['default']
    Toolbar: typeof import('./src/components/schedule/toolbar/Toolbar.vue')['default']
    ToolbarSettings: typeof import('./src/components/schedule/toolbar/ToolbarSettings.vue')['default']
    UISelect: typeof import('./src/components/global/UISelect.vue')['default']
    UITextarea: typeof import('./src/components/global/UITextarea.vue')['default']
    Week: typeof import('./src/components/schedule/list/Week.vue')['default']
    WeekPicker: typeof import('./src/components/global/WeekPicker.vue')['default']
  }
}
